# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
script: ./travis-config.bash
sudo: false
warnings_are_errors: false
cache: packages
r_github_packages: jdreyf/ezlimma
bioc_packages: limma

# from https://github.com/stan-dev/rstan/issues/569
before_install:
  - Rscript -e 'update.packages(ask = FALSE)'
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++-6 -std=c++1y -fPIC" >> ~/.R/Makevars

output:
    pdf_document:
        latex_engine: xelatex
after_success:
- Rscript -e 'covr::codecov()'