# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
warnings_are_errors: false
cache: packages
script: ./travis-config.sh
r_github_packages: jdreyf/ezlimma
bioc_packages: limma
before_install:
  - Rscript -e 'update.packages(ask = FALSE)'
output:
     pdf_document:
         latex_engine: xelatex
after_success:
- Rscript -e 'covr::codecov()'