#'Pathway Analysis via NeTwork Smoothing
#'
#'This is the main function of the \code{PANTS} package, which implements the PANTS algorithm
#'of Pathway Analysis (and optionally integration) via Network Smoothing for group contrasts.
#'
#'@param object A matrix-like data object containing log-ratios or log-expression values for a
#'series of samples, with rows corresponding to features and columns to samples.
#'@param phenotype.v A vector of phenotypes of strings the same length as number of samples in \code{object}.
#'If the vector is named, the names must match the column names of \code{object}.
#'@param contrasts.v A named vector of constrasts. The constrasts must refer to the phenotypes
#'in \code{phenotype.v}. Their order defines the order they are passed to \code{score_fcn}.
#'@param ker The Laplacian kernel matrix.
#'@param Gmat The feature by pathway inclusion matrix, indicating which features are in which pathways.
#'@param score_fcn A function that transforms the t-statistics from the contrasts. \code{identity} is 
#'the trivial identity function returning its argument. Its input must be a vector of same 
#'length as number of elements in \code{contrasts.v}. Its output must be a scalar.
#'@param nperm Number of permutations to perform to evaluate significance of pathways.
#'@param ret.null.mats If TRUE, return matrices with null distributions for features and pathways.
#'@param verbose Logical indicating if the permutation number should be output every 500 permutations.
#'@param alternative A character string specifying the alternative hypothesis.
#'@details Scores for features in the kernel but not in the data are assigned a value of zero by default for sparsity.
#'Scores for features and pathways are compared to null scores, which are generated by permuting the phenotypes and 
#'rerunning the algorithm.
#'@return List of length at least two, with elements \code{pwy.stats} and \code{feature.stats}, each containing a data frame
#'of statistics.
#'@export

pants <- function(object, phenotype.v, contrasts.v, ker, Gmat, score_fcn=identity, nperm=10^4, ret.null.mats=FALSE, verbose=TRUE, 
                  alternative=c("two.sided", "less", "greater")){
  stopifnot(length(intersect(rownames(ker), rownames(object)))>0, any(rownames(Gmat) %in% colnames(ker)),
            colnames(object)==names(phenotype.v))
  alternative <- match.arg(alternative)
  
  score.v <- score_features(object=object, phenotype.v=phenotype.v, 
                            contrasts.v=contrasts.v, score_fcn=score_fcn)
  
  #feature scores in permutations, 74% dense but later combine with a sparse (empty) matrix
  score.mat <- Matrix(0, nrow=nrow(object), ncol=nperm, dimnames = list(rownames(object), paste0('perm', 1:nperm)))
  for (perm in 1:nperm){
    #must set permuted names to NULL st limma_contrasts doesn't complain thay they clash with colnames(object)
    pheno.tmp <- setNames(phenotype.v[sample(1:length(phenotype.v))], nm=NULL)

    score.mat[,perm] <- score_features(object=object, phenotype.v=pheno.tmp, contrasts.v=contrasts.v, score_fcn=score_fcn)
    if (verbose){
      if (perm %% 500 == 0) cat("permutation", perm, "\n")
    }
  }

  mm <- match_mats(score.mat = cbind(v=score.v, score.mat), ker=ker, Gmat=Gmat)
  score.mat <- mm$score.mat[,-1]; score.v <- mm$score.mat[,1]; ker <- mm$ker; Gmat <- mm$Gmat
  rm(mm) #to save memory
  
  ##feature p-values (for plotting)
  #features in object & in kernel
  feature.stats <- data.frame(score = score.v, matrix(NA, nrow=length(score.v), ncol=3,
dimnames=list(rownames(score.mat), c("z", "pval", "FDR"))))
  #need to coerce score.mat to matrix to prevent rowSums error
  feature.stats[,c("z", "pval")] <- p_ecdf(eval=score.v, scores.mat = as.matrix(score.mat), alternative = alternative)
  feature.stats[,"FDR"] <- p.adjust(feature.stats[,"pval"], method="BH")

  ##need to compare to pwys, sometimes runs out of memory
  pwy.v <- (score.v %*% ker %*% Gmat)[1,]
  pwy.mat <- as.matrix(Matrix::t(Matrix::crossprod(score.mat, ker) %*% Gmat))

  nfeats.per.pwy <- Matrix::colSums(Gmat!=0)
  pwy.stats <- data.frame(nfeatures=nfeats.per.pwy, feat.score.avg=pwy.v/nfeats.per.pwy, z=NA, pval=NA)
  rownames(pwy.stats) <- colnames(Gmat)
  pwy.stats[,c("z", "pval")] <- p_ecdf(eval.v=pwy.v, scores.mat=pwy.mat, alternative = alternative)
  pwy.stats$FDR <- p.adjust(pwy.stats$pval, method='BH')
  pwy.stats <- pwy.stats[order(pwy.stats$pval, -abs(pwy.stats$feat.score.avg)),]

  res <- list(pwy.stats=pwy.stats, feature.stats=feature.stats)
  if (ret.null.mats){
    res$null.feature.mat <- score.mat
    res$null.pwy.mat <- pwy.mat
  }
  return(res)
}