#' Pathway Analysis via network smoothing using Hitman
#' 
#' Pants algorithm for pathway mediation analysis with Hitman and network smoothing.
#' 
#' @param exposure A numeric vector or matrix of exposures.
#' @param covariates Numeric vector or matrix of covariates.
#' @inheritParams pants
#' @inheritParams ezlimma::limma_contrasts
#' @inheritParams ezlimma::limma_cor
#' @inheritParams ezlimma::roast_contrasts
#' @details Scores for features in the kernel but not in the data are assigned a z-score of zero by default for sparsity.
#' Scores for features and pathways are compared to null scores, which are generated by permuting the columns of 
#' \code{object} and rerunning the algorithm. These are the stats returned in \code{feature.stats}. However, \code{pants}
#' accepts \code{feat.tab} with statistics from \code{ezlimma} per-feature analysis for the Excel file to link to;
#' these may be more precise, since they don't rely on a limited number of permutations. If \code{feat.tab} is \code{NULL},
#' the Excel file links to tables derived from \code{feature.stats}.

#' For \code{\link[parallel]{makeCluster}}, the cluster \code{type} depends on the OS, which is tested in the body
#' of the function using \code{.Platform$OS.type}.
#' 
#' If \code{!is.na(name)}, an Excel file with "_pants_hitman.xlsx" appended to the name gets written out with links to 
#' CSVs containing the statistics of features most affecting the pathway's score. These features are selected as those
#' with the largest magnitude impact score, and can be visualized with \code{\link[PANTS]{plot_pwy}}. Depending on \code{ker}, 
#' pathways may be affected via smoothing by features outside the pathway.
#' 
#' @return List of at least two data frames:
#' \describe{
#'    \item{\code{pwy.stats}}{A data frame with columns 
#'    \describe{
#'    \item{\code{nfeatures}}{number of features in the pathway} 
#'    \item{\code{feat.score.avg}}{sum of smoothed scores of the pathway's features / \code{nfeatures}. This score is compared
#'    to scores in permutations. Only included if \code{ret.null.mats==TRUE}.}
#'    \item{\code{z}}{pathway permutation z-score (larger is more significant)}
#'    \item{\code{p}}{pathway permutation p-value} 
#'    \item{\code{FDR}}{pathway FDR calculated from p-values with \code{p.adjust(p, method='BH')}}
#'    }}
#'    \item{\code{feature.stats}}{A data frame with columns
#'    \describe{
#'    \item{\code{score}}{feature's score, which is p-value from \code{\link[ezlimma]{hitman}} transformed into z-score 
#'    (larger is more significant)}
#'    \item{\code{z}}{feature z-score (larger is more significant) relative to this feature's scores in permutation 
#'    without smoothing. This should be similar to \code{score} if the permutation null distribution matches the 
#'    theoretical null distribution.} 
#'    \item{\code{p}}{feature's permutation p-value} 
#'    \item{\code{FDR}}{feature's FDR from permutation \code{p}}
#'    }}
#'    And if \code{ret.null.mats} is TRUE:
#'    \item{\code{null.feature.mat}}{Matrix with features as rows and permutations as columns, where each element represents
#'    the score of that feature in that permutation}
#'    \item{\code{null.pwy.mat}}{Matrix with pathways as rows and permutations as columns, where each element represents
#'    the score of that pathway in that permutation}
#'  }
#' @export

pants_hitman <- function(object, exposure, phenotype, Gmat, covariates=NULL, ker=NULL, feat.tab=NULL, ntop=5, nperm=10^4-1, 
                         ret.null.mats=FALSE, min.nfeats=0, ncores=1, name=NA, seed=0){
  if (is.null(ker)){
    ker <- diag_kernel(object=object, Gmat=Gmat)
  }
  
  stopifnot(length(intersect(rownames(ker), rownames(object))) > 0, any(rownames(Gmat) %in% colnames(ker)), 
            ncol(object)==length(phenotype), ncol(object)==nrow(as.matrix(exposure)), colnames(object)==names(phenotype))
  
  if (ncol(as.matrix(exposure))==1){
    stopifnot(colnames(object)==names(exposure))
  } else {
    stopifnot(colnames(object)==rownames(exposure))
  }
  
  zeallot::`%<-%`(c(Gmat, nfeats.per.pwy), subset_gmat(object=object, Gmat=Gmat, min.nfeats=min.nfeats))
  
  lmed <- ezlimma::hitman(E=exposure, M=object, Y=phenotype, covariates=covariates)
  # transform to one-sided z-score
  score.v <- stats::qnorm(p=lmed[rownames(object), "EMY.p"], lower.tail = FALSE)
  
  # feature scores in permutations
  cl.type <- ifelse(.Platform$OS.type=='windows', "PSOCK", "FORK")
  cl <- parallel::makeCluster(spec=ncores, type=cl.type)
  set.seed(seed)
  perms <- lapply(seq_len(nperm), function(i) sample.int(ncol(object)))
  score.mat <- parallel::parSapply(cl, perms, function(perm){
    #must set permuted names to NULL st limma_contrasts doesn't complain that they clash with colnames(object)
    object.tmp <- object[,perm]
    #to avoid names error in stopifnot
    colnames(object.tmp) <- colnames(object)
    
    lmed.tmp <- ezlimma::hitman(E=exposure, M=object.tmp, Y=phenotype, covariates=covariates)
    stats::qnorm(p=lmed.tmp[rownames(object), "EMY.p"], lower.tail = FALSE)
  })
  dimnames(score.mat) <- list(rownames(object), paste0('perm', 1:nperm))
  parallel::stopCluster(cl=cl)
  
  mm <- match_mats(score.mat = cbind(v=score.v, score.mat), ker=ker, Gmat=Gmat)
  # 1st column contains non-permuted scores
  score.mat <- mm$score.mat[,-1]; score.v <- mm$score.mat[,1]; ker <- mm$ker; Gmat <- mm$Gmat
  rm(mm) #to save memory
  
  # feature p-values (for plotting)
  #features in object & in kernel
  feature.stats <- data.frame(score = score.v, matrix(NA, nrow=length(score.v), ncol=3,
                                                      dimnames=list(rownames(score.mat), c("z", "p", "FDR"))))
  # need to coerce score.mat to matrix to prevent rowSums error
  feature.stats[,c("z", "p")] <- p_ecdf(eval.v=score.v, score.mat = as.matrix(score.mat), alternative = "greater")
  feature.stats[,"FDR"] <- stats::p.adjust(feature.stats[,"p"], method="BH")
  
  # need to compare to pwys, sometimes runs out of memory
  pwy.v <- (score.v %*% ker %*% Gmat)[1,]
  pwy.mat <- as.matrix(Matrix::t(Matrix::crossprod(score.mat, ker) %*% Gmat))
  
  pwy.stats <- data.frame(nfeatures=nfeats.per.pwy, feat.score.avg=pwy.v/nfeats.per.pwy, z=NA, p=NA)
  rownames(pwy.stats) <- colnames(Gmat)
  pwy.stats[,c("z", "p")] <- p_ecdf(eval.v=pwy.v, score.mat=pwy.mat, alternative = "greater")
  pwy.stats$FDR <- stats::p.adjust(pwy.stats$p, method='BH')
  pwy.stats <- pwy.stats[order(pwy.stats$p, -pwy.stats$feat.score.avg),]
  
  # return res
  res <- list(pwy.stats=pwy.stats, feature.stats=feature.stats)
  if (ret.null.mats){
    res$null.feature.mat <- as.matrix(score.mat)
    res$null.pwy.mat <- as.matrix(pwy.mat)
  } else {
    #only include "feat.score.avg" if ret.null.mats
    res$pwy.stats <- res$pwy.stats[,setdiff(colnames(res$pwy.stats), "feat.score.avg")]
  }
  
  # write xlsx file with links
  if (!is.na(name)){
    if (is.null(feat.tab)) feat.tab <- feature.stats
    write_pants_xl(score.v=score.v, pwy.tab=res$pwy.stats, feat.tab=feat.tab, Gmat=Gmat, ker=ker, alternative="greater", 
                   name=paste0(name, "_pants_hitman"), ntop=ntop)
  }
  return(res)
}